#!/bin/bash
# B3 Hive all-in-one container entrypoint
#
# 1. Ensure /data/b3coin.conf exists (generated from env on FIRST RUN only —
#    an existing conf is never overwritten).
# 2. Start b3coind in the foreground (chain data in /data).
# 3. If RUN_UI is not "false", start the backend (FastAPI) which serves the
#    UI and talks to the node over loopback RPC.
# 4. Supervise: daemon death stops the container (restart policy handles it);
#    backend death is tolerated and restarted (up to 5 times).

set -euo pipefail

B3_DATA_DIR="${B3_DATA_DIR:-/data}"
RUN_UI="${RUN_UI:-true}"
WEB_PORT="${WEB_PORT:-8080}"
CONF="${B3_DATA_DIR}/b3coin.conf"
BACKEND_MAX_RESTARTS=5

log() { echo "[entrypoint] $*"; }

generate_rpc_secret() {
    # Read exactly 16 bytes from /dev/urandom and hex-encode them (32 chars).
    # NOTE: never use `tr ... < /dev/urandom | head -c N` here — head closes the
    # pipe, tr gets SIGPIPE (141), and set -o pipefail kills the entrypoint.
    head -c 16 /dev/urandom | od -An -tx1 | tr -d ' \n'
}

# --- 0. Privilege setup ----------------------------------------------------
if [ "$(id -u)" = "0" ]; then
    # Started as root (docker default): fix data-dir ownership, run as b3coin.
    chown -R b3coin:b3coin "${B3_DATA_DIR}" 2>/dev/null || true
    run_as() { gosu b3coin "$@"; }
else
    run_as() { "$@"; }
fi

# --- 1. Generate b3coin.conf on FIRST RUN only ------------------------------
if [ ! -f "${CONF}" ]; then
    log "No b3coin.conf found — generating from environment (first run)"
    RPC_USER="${RPC_USER:-b3coinrpc}"
    if [ -z "${RPC_PASSWORD:-}" ]; then
        RPC_PASSWORD="$(generate_rpc_secret)"
        log "RPC_PASSWORD not set — generated a random one"
    fi
    RPC_PORT="${RPC_PORT:-32647}"

    cat > "${CONF}.tmp" <<EOF
# Generated by the B3 Hive container entrypoint on first run.
# Edit freely — this file is NOT overwritten on subsequent runs or upgrades.

# Network
txindex=1
listen=1
listenonion=0

# RPC — loopback only (the backend proxy is the only RPC client)
rpcbind=127.0.0.1
rpcallowip=127.0.0.1
rpcport=${RPC_PORT}
rpcuser=${RPC_USER}
rpcpassword=${RPC_PASSWORD}

# Staking: v1.1.4 has NO 'staking=' conf option (it is ignored with a
# warning). Staking is started via the wallet RPC (startstaking) — the UI
# will expose this in a later phase. Nothing to configure here.

# Wallet
disablewallet=0
EOF
    chown b3coin:b3coin "${CONF}.tmp" 2>/dev/null || true
    chmod 600 "${CONF}.tmp"
    mv "${CONF}.tmp" "${CONF}"
    log "Generated ${CONF}"
    log "NOTE: RPC credentials live only in ${CONF} — delete that file to regenerate (loses no chain data)"
fi

# Read back the EFFECTIVE RPC settings from the conf — it is the source of
# truth (the user may have edited it since it was generated).
RPC_USER="$(grep -E '^rpcuser=' "${CONF}" | tail -1 | cut -d= -f2-)"
RPC_PASSWORD="$(grep -E '^rpcpassword=' "${CONF}" | tail -1 | cut -d= -f2-)"
RPC_PORT="$(grep -E '^rpcport=' "${CONF}" | tail -1 | cut -d= -f2-)"
RPC_PORT="${RPC_PORT:-32647}"

# --- 2. Start the daemon -----------------------------------------------------
log "Starting b3coind (datadir=${B3_DATA_DIR})"
run_as b3coind \
    -datadir="${B3_DATA_DIR}" \
    -printtoconsole \
    -daemon=0 &
DAEMON_PID=$!

# --- 3. Backend (UI) --------------------------------------------------------
start_backend() {
    log "Starting backend (UI) on :${WEB_PORT}"
    B3_RPC_HOST=127.0.0.1 \
    B3_RPC_PORT="${RPC_PORT}" \
    B3_RPC_USER="${RPC_USER}" \
    B3_RPC_PASSWORD="${RPC_PASSWORD}" \
    run_as python -m uvicorn app.main:app --host 0.0.0.0 --port "${WEB_PORT}" &
    BACKEND_PID=$!
}

BACKEND_PID=""
BACKEND_RESTARTS=0
if [ "${RUN_UI}" != "false" ]; then
    start_backend
else
    log "RUN_UI=false — headless mode (daemon only)"
fi

# --- 4. Supervise -------------------------------------------------------------
terminate() {
    log "SIGTERM/SIGINT received — shutting down"
    if [ -n "${BACKEND_PID}" ]; then
        kill -TERM "${BACKEND_PID}" 2>/dev/null || true
    fi
    kill -TERM "${DAEMON_PID}" 2>/dev/null || true
    wait 2>/dev/null
    exit 0
}
trap terminate TERM INT

while true; do
    # Daemon death stops the container.
    if ! kill -0 "${DAEMON_PID}" 2>/dev/null; then
        wait "${DAEMON_PID}"
        DAEMON_EXIT=$?
        log "b3coind exited (code ${DAEMON_EXIT}) — shutting down container"
        if [ -n "${BACKEND_PID}" ]; then
            kill -TERM "${BACKEND_PID}" 2>/dev/null || true
        fi
        wait 2>/dev/null
        exit "${DAEMON_EXIT}"
    fi
    # Backend death is tolerated: restart it (bounded).
    if [ -n "${BACKEND_PID}" ] && ! kill -0 "${BACKEND_PID}" 2>/dev/null; then
        wait "${BACKEND_PID}" || true
        BACKEND_RESTARTS=$((BACKEND_RESTARTS + 1))
        if [ "${BACKEND_RESTARTS}" -gt "${BACKEND_MAX_RESTARTS}" ]; then
            log "backend crashed ${BACKEND_RESTARTS} times — giving up (daemon keeps running headless)"
            BACKEND_PID=""
        else
            log "backend exited — restarting (attempt ${BACKEND_RESTARTS}/${BACKEND_MAX_RESTARTS})"
            start_backend
        fi
    fi
    # Recovery command polling: the monitor writes a command to
    # /data/recovery.cmd when stall_level is restart or reindex.
    RECOVERY_CMD="${RECOVERY_CMD_FILE:-/data/recovery.cmd}"
    if [ -f "${RECOVERY_CMD}" ]; then
        CMD=$(cat "${RECOVERY_CMD}")
        rm -f "${RECOVERY_CMD}"
        log "recovery command: ${CMD}"
        case "${CMD}" in
            restart)
                log "restarting b3coind (stall recovery)"
                kill -TERM "${DAEMON_PID}" 2>/dev/null || true
                wait "${DAEMON_PID}" 2>/dev/null || true
                sleep 5
                run_as b3coind -datadir="${B3_DATA_DIR}" -printtoconsole -daemon=0 &
                DAEMON_PID=$!
                ;;
            reindex)
                log "restarting b3coind with -reindex (stall recovery)"
                kill -TERM "${DAEMON_PID}" 2>/dev/null || true
                wait "${DAEMON_PID}" 2>/dev/null || true
                sleep 5
                run_as b3coind -datadir="${B3_DATA_DIR}" -printtoconsole -daemon=0 -reindex &
                DAEMON_PID=$!
                ;;
            *)
                log "unknown recovery command: ${CMD} — ignoring"
                ;;
        esac
    fi
    sleep 5
done